---

- name: Install the monitoring packages
  apt:
    name: "{{ item }}"
  loop:
  - collectd

- name: Deploy the collectd conf file
  template:
    src: collectd.conf.j2
    dest: /etc/collectd/collectd.conf
    backup: yes
    force: yes

- name: Enable collectd at boot
  systemd:
    name: collectd
    enabled: yes

- name: Restart collectd
  systemd:
    name: collectd
    state: restarted
