---

- name: Install the monitoring packages
  apt:
    name: "{{ item }}"
  loop:
  - collectd
  - hddtemp

- name: Deploy the collectd conf file
  template:
    src: collectd.conf.j2
    dest: /etc/collectd/collectd.conf
    backup: yes
    force: yes

- name: Remove the old collectd conf backups
  shell: find /etc/collectd/ -name collectd.conf.* -mtime +10 -type f -delete

- name: Create collectd log folder
  file:
    path: /var/log/collectd/
    state: directory

- name: Enable services at boot
  systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
  - hddtemp
  - collectd

- name: Restart services
  systemd:
    name: "{{ item }}"
    state: restarted
  loop:
  - hddtemp
  - collectd
