---

- name: Install the monitoring packages
  apt:
    name: "{{ item }}"
  loop:
  - collectd

- name: Backup the previous collectd conf file
  command: cp /etc/collectd/collectd.conf /etc/collectd/collectd.conf.backup

- name: Deploy the collectd conf file
  copy:
    src: collectd.conf
    dest: /etc/collectd/collectd.conf

- name: Enable collectd at boot
  systemd:
    name: collectd
    enabled: yes

- name: Restart collectd
  systemd:
    name: collectd
    state: started
