---

- name: Update apt cache
  apt: update_cache=yes

- name: Upgrade all safe packages
  apt: upgrade=safe

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes